

const mongoose = require('mongoose');

/**
 * Connects to a MongoDB database using Mongoose.
 */
const connectDb = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URL);
    console.log('Database connected');
  } catch (error) {
    console.log(error.stack);
    process.exit(1);
  }
};

module.exports = connectDb;

// Generated by CodiumAI

describe('connectDb', () => {

    // Throws an error if MONGO_URL environment variable is not set
    it('should throw an error if MONGO_URL environment variable is not set', async () => {
      delete process.env.MONGO_URL;
      await expect(connectDb()).rejects.toThrow('MONGO_URL environment variable is not set');
    });
});
