

const mongoose = require('mongoose');

/**
 * Connects to a MongoDB database using Mongoose.
 */
const connectDb = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URL);
    console.log('Database connected');
  } catch (error) {
    console.log(error.stack);
    process.exit(1);
  }
};

module.exports = connectDb;

// Generated by CodiumAI

describe('connectDb', () => {

    // Fails to connect to MongoDB database
    it('should throw an error if fails to connect to MongoDB database', async () => {
      const mockConnect = jest.spyOn(mongoose, 'connect').mockRejectedValue(new Error('Connection failed'));
      const mockExit = jest.spyOn(process, 'exit').mockImplementation(() => {});
      await connectDb();
      expect(mockConnect).toHaveBeenCalledWith(process.env.MONGO_URL);
      expect(console.log).toHaveBeenCalledWith('Connection failed');
      expect(mockExit).toHaveBeenCalledWith(1);
    });
});
