

const mongoose = require('mongoose');

/**
 * Connects to a MongoDB database using Mongoose.
 */
const connectDb = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URL);
    console.log('Database connected');
  } catch (error) {
    console.log(error.stack);
    process.exit(1);
  }
};

module.exports = connectDb;

// Generated by CodiumAI

describe('connectDb', () => {

    // Successfully connects to MongoDB database
    it('should successfully connect to MongoDB database', async () => {
      const mockConnect = jest.spyOn(mongoose, 'connect');
      await connectDb();
      expect(mockConnect).toHaveBeenCalledWith(process.env.MONGO_URL);
      expect(console.log).toHaveBeenCalledWith('Database connected');
    });
});
